y-height: 400 #The height to teleport
enable-sound: true
sound: ENTITY_EVOKER_PREPARE_SUMMON #List of sounds at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
volume: 1
pitch: 1
reset-fall-distance: false #If this is enabled, the fall distance of the player will be reset after teleporting
cancel-damage: true #If this is enabled, the player will get no void damage.
change_dimensions: false